/** Built-in product text; user content retains its original language. */
export const interactionCopy = {
  copied: 'Copied', lines: 'lines',
  copySent: 'Copy sent; clipboard confirmation unavailable',
  copyReasons: { empty: 'Nothing to copy', unavailable: 'Clipboard tool unavailable',
    write: 'Clipboard write failed', timeout: 'Clipboard tool timed out',
    'too-large': 'Content exceeds clipboard limit', cancelled: 'Copy cancelled' },
  stopServicesShort: '^C stop services', approveTool: 'y approve', rejectTool: 'n/Enter reject',
  saveSettings: 'Enter save', modeLabel: 'switch mode',
  idle: ['Idle', 'Idle'], starting: ['Start', 'Starting'], waiting: ['Wait', 'Waiting for model'],
  thinking: ['Think', 'Thinking'], generating: ['Write', 'Generating'],
  preparingTool: ['Prep', 'Preparing tool'], tool: ['Tool', 'Running tool'],
  confirming: ['Ask', 'Awaiting confirmation'], stopping: ['Stop', 'Stopping'],
  compacting: ['Pack', 'Compacting context'], retrying: ['Retry', 'Retrying'],
  ended: ['Done', 'Done'], interrupted: ['Abort', 'Interrupted'], failed: ['Error', 'Failed'],
  readFile: ['Tool', 'Running tool read_file'], writeFile: ['Tool', 'Running tool write_file'],
  command: ['Tool', 'Running tool bash'],
  queue: 'Q', pending: 'pending', context: 'Context', contextUnknown: 'Context ?',
  sessionInput: 'Session input', output: 'output', estimatedCost: 'Cost',
  speed: 'Run average', elapsed: 'Elapsed', services: 'Services',
  send: 'Enter send', enqueue: 'Enter queue', newline: '^J newline',
  sendLong: 'Enter send', enqueueLong: 'Enter queue', newlineLong: 'Ctrl+J newline',
  interrupt: 'Esc x2 stop', interruptAgain: 'Esc stop', forceStop: 'Esc force',
  startingHint: 'Starting; please wait', cancelStart: 'Esc x2 cancel', cancelStartAgain: 'Esc cancel',
  copy: 'Ctrl+C copy', copying: 'Copying', copyFailed: 'Copy failed', copyCleanup: 'Copy failed; cleaning up',
  close: 'Esc close', closeCompletion: 'Esc menu', executeCommand: 'Enter command',
  complete: 'Tab complete', select: 'Up/Down select', scroll: 'PgUp/PgDn scroll',
  confirm: 'Enter confirm', stopServices: 'Ctrl+C stop services', exit: 'Ctrl+C x2 exit',
  exitDraft: 'Ctrl+C x2 clear input, x3 exit',
  help: '/help', shiftNewline: 'Shift+Enter newline needs terminal support',
  mode: 'Shift+Tab switch mode', update: '/update',
  idlePlaceholder: 'Ask a question or describe a task...', runningPlaceholder: 'Add a follow-up...',
} as const;
